version: '3'
services:
    mysql:
        container_name: MYSQL-DB
#        image: 'mysql:5.6.31'
        image: 'mysql'
        command:
            - --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
          - ./customconf:/etc/mysql/conf.d
          - ./datadir:/var/lib/mysql
          - ./plugins:/usr/lib/mysql/plugin
          - ./scripts:/docker-entrypoint-initdb.d/
        environment:
          MYSQL_ROOT_PASSWORD: mypassword
          MYSQL_DATABASE: DATABASE_TEST